### ISSUE TITLE
HLASM Syntax highlighting issues

### ISSUE THREAD

**Issue by cybersorcerer** [IBM/zopeneditor-about#118]
## Development environment used

- Z Open Editor version: 1.2.0
- Editor Platform
  - [X ] Visual Studio Code
  
- Editor Platform Version:
    Version: 1.54.3 (user setup)
    Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
    Date: 2021-03-15T10:55:45.459Z
    Electron: 11.3.0
    Chrome: 87.0.4280.141
    Node.js: 12.18.3
    V8: 8.7.220.31-electron.0
    
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
  Windows 10 Version 1909  Build 18363.1440

- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): 
No

## Problem Description

Detailed steps for reproducing the problem:

1. First step

- Open any file with high level assembler
- Write instruction starting before column 16, syntax highlighting is fine and code completion works
- Write a instaruction beginning at column 16, no syntax highlighting and code completion does not work anymore

### Expected behavior
Since it is perfectly valid to start writing instructions at column 16 syntax highlighting should work
Have a look at the attached screen shot line 132 starts at column 15 syntax highlighting as expected. Line 133 starts at column 16, syntax highlighting is messed up. The prgram assembles and links just fine.

greetings from germany!

![syntax_highlighting](https://user-images.githubusercontent.com/33680802/113097455-3362e180-91f7-11eb-8113-b9e432725ad7.PNG)

**Comment by phaumer** [comment]
Vielen Dank.

**Comment by cybersorcerer** [comment]
Hi,

any news on this issue? Just updated to 1.2.1 and the problem still exists.  It is really annoying.

Thanks

Ronny

**Comment by phaumer** [comment]
We want to still fix it. We will update this item when we have an update.

**Comment by phaumer** [comment]
@cybersorcerer trying to reproduce your issue: I can see the problems with the syntax highlighting, but I cannot reproduce issues with code completion. Even if the text appears in comments-color I can still code-complete them. See screen shot: I still get Init being offered in the drop-down. Can you describe in more detail how to reproduce it?

![image](https://user-images.githubusercontent.com/4391934/116948105-5e47b780-ac33-11eb-96fe-3372a49bdf42.png)

**Comment by cybersorcerer** [comment]
@phaumer unfortunately i can't. The only thing that i can think of is the location of the source code. My source code is not located on my PC's file system.  My source code is located inside my USS file system and is mounted to my PC using NFS.  As you can see from the following screenshots. I did the same as you and code completion stops working as soon as the code starts at 16:
![sc1](https://user-images.githubusercontent.com/33680802/116958516-355b0d00-ac9b-11eb-91ce-6febc7fe34cf.png)

![sc2](https://user-images.githubusercontent.com/33680802/116958528-3f7d0b80-ac9b-11eb-845e-222424f1839a.png)

**Comment by phaumer** [comment]
@cybersorcerer, we made some fixes in v1.2.5 for the syntax highlighting and code completion. There is still one case with code completion with continuation lines open that we will address in a future release. I leave this item open until then.

**Comment by cybersorcerer** [comment]
@phaumer , 
just installed 1.2.5 and did some testing. This looks much better now 👍 Thanks!

**Comment by phaumer** [comment]
@cybersorcerer hopefully we fixed now all the the issues you observed in v1.2.6 now available on the Marketplace. Let us know if it works for you as well.

**Comment by cybersorcerer** [comment]
Hi Peter,

unfortunately it still does not work. Same problem with highlighting in continuation lines as  before. VS Code Release 1.59.1, IBM Z Open Editor 1.2.6. Have a look at the screenshots below:
The definition starting on line 2333, continued at 2334 the colorization is wrong, Definitions starting at 2335 to 2342 are looking ok to me, 2344 is wrong again.

***@***.***

Macro Definitions with continuation lines are better but still incorrect only the first looks like only the first parameter on each line is correct, all others on the same line are incorrect

***@***.***

As long as each parameter is on a new line it looks better:

***@***.***

Hope that helped

greetings

Ronny

**Comment by cybersorcerer** [comment]
@phaumer unfortunately it still does not work. Same problem with highlighting in continuation lines as  before. VS Code Release 1.59.1, IBM Z Open Editor 1.2.6. Have a look at the screenshots below:
The definition starting on line 2333, continued at 2334 the colorization is wrong, Definitions starting at 2335 to 2342 are looking ok to me, 2344 is wrong again
![sc1](https://user-images.githubusercontent.com/33680802/130177224-237d5723-eb10-4d64-9fea-eefe9561cdd0.PNG)

Macro Definitions with continuation lines are better but still incorrect only the first looks like only the first parameter on each line is correct, all others on the same line are incorrect

![sc2](https://user-images.githubusercontent.com/33680802/130177312-35ec354d-960d-493b-9a74-7cf874d591bf.png)

As long as each parameter is on a new line it looks better:

![sc3](https://user-images.githubusercontent.com/33680802/130177374-e062569d-e007-4974-93ce-ca2b11de198d.png)

Hope that helped

greetings

Ronny

**Comment by phaumer** [comment]
We improved this in v1.4.1. See the [Know issues](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html#hlasm) list for what is left. Let's open new issues for other important items to fix.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] HLASM Syntax highlighting issues (#118)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
