### ISSUE TITLE
User Build - Unable to upload file to uss with Zowe profile ZOSMF

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#235]
## Development environment used

- Z Open Editor version: 2.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.66.2
- Operating System: Windows 10 20H2
- Java Version: 1.8
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Transferring a file to USS using the "Run IBM User build" command systematically fails when using a ZOSMF-type Zowe profile.

This seems related to interpreting the .gitattributes file to extract the codepage to use for uploading and tagging the file to USS.

* Declaring encoding `ibm-1147`

![image](https://user-images.githubusercontent.com/63861965/164970040-dc1c0de2-6fe5-4d1b-a0c7-66c0d42105e4.png)

```
Uploading file c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\minimal.cbl to /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl with encoding ibm-1147
Stopping User Build. An error occurred uploading required files: Invalid character in header content ["X-IBM-Data-Type"]
```

* Declaring encoding `1147`

![image](https://user-images.githubusercontent.com/63861965/164970082-2b645223-90c8-4230-a98b-1ad0802bfb56.png)

```
Uploading file c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\minimal.cbl to /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl with encoding 1147
Stopping User Build. An error occurred uploading required files: Invalid character in header content ["X-IBM-Data-Type"]
```

* Declaring encoding `IBM-1147`

![image](https://user-images.githubusercontent.com/63861965/164970143-fb9ad48f-d24f-495c-af6c-b2fd93743fab.png)

```
Uploading file c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\minimal.cbl to /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl with encoding IBM-1147
Stopping User Build. An error occurred uploading required files: Invalid character in header content ["X-IBM-Data-Type"]
```

* Declaring encoding `IBM-1047`

![image](https://user-images.githubusercontent.com/63861965/164970397-21b84689-5b6a-4ae8-9975-307f38fd8dc6.png)

```
Uploading file c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\minimal.cbl to /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl with encoding IBM-1047
Stopping User Build. An error occurred uploading required files: Invalid character in header content ["X-IBM-Data-Type"]
```

* Declaring no encoding 

![image](https://user-images.githubusercontent.com/63861965/164970531-ff8d18e2-aef1-461f-b5fd-0808b3d62a16.png)

```
Uploading file c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\minimal.cbl to /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl
Using SSH profile GMVS-SSH
Executing SSH command: 
chtag -tc undefined /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl
@@START OF COMMAND@@
$ chtag -tc undefined /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COB
$
$ /environn-techleads-sandbox/src/S9T/COBO                                    <L/minimal.cbl
FSUMF174 chtag: You must enter a codeset name or a ccsid between 0 and 65535 (USHRT_MAX).
$ exit $?
Stopping User Build. An error occurred uploading required files: Error: Something went wrong executing SSH command chtag -tc undefined /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/minimal.cbl
```

**Comment by FALLAI-Denis** [comment]
Hi,

Could the problem encountered be related to this other problem?
https://github.com/zowe/zowe-cli/issues/1383

What type of terminal does IBM User Build use to place its Zowe orders?

**Comment by FALLAI-Denis** [comment]
Hi,

Things seem to have gotten worse with the switch to Zowe CLI V2 and the migration of Zowe profiles from V1 to V2: now the upload of elements on USS freezes.

```
=====================
Running User Build...
Identified the local root workspace path as c:\Trv\DepotsGIT\environn-techleads-sandbox
---------------------
Checking the ZAPP file or workspace settings...
DBB ZAPP or workspace settings should be defined in either your repository's zapp.yaml, zapp.json or .vscode/settings.json file.
    command: /bin/echo
    buildScriptArgs: --userBuild,--workspace /u/J070188/vscode,--application environ-techleads-sandbox/src,--hlq J070188.VSCODE.USERBUILD,--outDir /u/J070188/vscode/logs
    buildScriptPath: /tmp
    additionalDependencies: application-conf
---------------------
Checking user settings...
User settings should be defined in your VS Code or Theia Settings under zopeneditor.userbuild.userSettings
    localWorkspacePath: **Optional setting is missing**
    dbbWorkspace: /u/J070188/vscode
    dbbHlq: J070188.VSCODE.USERBUILD
    dbbLogDir: /u/J070188/vscode/logs
---------------------
The default Zowe CLI profile specified as GMVS in zopeneditor.zowe setting. Will try loading that.
Using Zowe profile GMVS
(frozen...)
```

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

We are starting work on setting up IBM DBB. It is imperative for us that the problem described here is solved very quickly

Thanks.

**Comment by phaumer** [comment]
@FALLAI-Denis we are not able to reproduce this. We asked the local tech sales people to contact you to explore this with you directly.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

I discussed with the IBM France representatives who are supporting us in setting up IBM DBB about the problems encountered.
We agreed to analyze with the IBM team the problem in detail with the implementation of IBM DBB, from the beginning of June.

I will already see why the switch to Zowe CLI V2 caused a new problem...may be a problem in profile management, (Lots of issues around profile management with the move to Zowe CLI V2...).

Looking forward to, the tests made with Zowe CLI V1 show that the problem is related to the formatting of the "X-IBM-Data-Type" header from the zos-working-tree-encoding information extracted from the .gitattributes file.

If I don't provide a zos-working-tree-encoding value the problem disappears (but another one appears).
So it is probably around the analysis of the .gitattributes file that the problem lies.

The workspace files use crlf line terminators, (we are on a Windows platform), the zos-working-tree-encoding parameter is the last of the line. Wrongly extracting the "cr" character in the value?
VS Code workspace uses UTF-8 encoding by default.
The .gitattributes file is encoded in iso-8859-1.

Is there a way to see what Z Open Editor builds as a command and sends to z/OSMF (because it's z/OSMF that refuses the command), either locally on the workstation or by analyzing the network traffic, on the workstation, or on the z/OS system (in the past I have already taken network frame captures on z/OS... I am looking to see if I can find the procedure for dumping network frames) .

**Comment by phaumer** [comment]
@FALLAI-Denis you are right CRLF seems to be the problem. As a workaround you could convert your .gitattributes file locally to LF before running a build. (Just click on the CRLF in VS Code at the bottom-right, select LF and Save. You do not need to commit it as it just reads locally and use VS Code to revert the change once you finished building.) 

We want to provide a fix.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer 

I adapted my .gitattributes file to be with "lf" line endings:
![image](https://user-images.githubusercontent.com/63861965/169514231-2f05a29e-2496-41bb-b021-721b03439534.png)
It appears in VS Code as "Windows 1252", but it is "iso-8859-1".

I am under Zowe CLI V2.
I declared a zowe.config.json file and a zowe.config.user.json file at the root of the Workspace.
Confer [Zowe CLI V2 - Using environment variables in profile properties](https://github.com/zowe/zowe-cli/issues/1425)

Apparently Z Open Editor ignores these files present in the root of the Workspace, and uses those declared in my home directory, or combine both:
```
  - Zowe CLI API version used for profile management: 7
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found: GMVS(zosmf),EMVS(zosmf),EMVS-JENKINS(zosmf),GMVS-JENKINS(zosmf),SYSB-JENKINS(zosmf),TMVS-JENKINS(zosmf),SYSB(zosmf),TMVS(zosmf),GMVS-SSH(ssh),TMVS-SSH(ssh)
  - Zowe CLI files profile name specified in VS Code user settings: GMVS
  - Zowe CLI SSH profile name specified in VS Code user settings: GMVS-SSH
  - Zowe CLI files profile used for remote include files: GMVS
  - Zowe CLI SSH profile used: GMVS-SSH
```
Only "GMVS**" profiles are present in the zowe.config.json file of the Workspace... the other profiles are declared in the zowe.config.json file of my home directory, and should not be taken into account?

Anyway, the IBM User Build commands asks for credentials on each activation, even if they are saved, and freeze on the z/OSMF profile usage test, and this since the switch to Zowe CLI V2.

![image](https://user-images.githubusercontent.com/63861965/169519754-aed41c69-8f4e-4e33-9247-5951d1f2653d.png)

After going through Zowe Explorer, the credentials were again requested and saved, and no longer requested afterwards (stopping / restarting VS Code).

Back in Z Open Editor, credentials are no longer requested... but IBM User Build commands still freeze on z/OSMF profile test.

I deleted the zowe.config.json file present in my home directory.
Z Open Editor now only sees profiles defined in the Workspace zowe.config.json file:
```
  - Zowe CLI API version used for profile management: 7
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI profiles of types rse, zosmf or ssh found: GMVS(zosmf),GMVS-SSH(ssh)
  - Zowe CLI files profile name specified in VS Code user settings: GMVS
  - Zowe CLI SSH profile name specified in VS Code user settings: GMVS-SSH
  - Zowe CLI files profile used for remote include files: GMVS
  - Zowe CLI SSH profile used: GMVS-SSH
```

IBM User Build commands always freeze... and don't ask for credentials...

**Comment by FALLAI-Denis** [comment]
I found the reason for the freezing the procedure!

After a very long time, a message appears in the log: Timed out waiting for password.
There is no prompt for entering user/password in VS Code...

```
Welcome to IBM User Build. Run User Build from the pop-up menu in an open editor with a COBOL, PL/I, or HLASM program.
Visit our IBM Docs to learn about IBM User Build here: https://www.ibm.com/docs/en/z-modernization-stack/2022.1.1?topic=code-building-cobol-pli-hlasm-programs-user-build.
=====================
Running setup for User Build...
Setup will upload files or folders that are defined in your ZAPP file or in .vscode/settings.json under "zopeneditor.userbuild.userSettings.additionalDependencies".
Checking the ZAPP file or workspace settings...
DBB ZAPP or workspace settings should be defined in either your repository's zapp.yaml, zapp.json or .vscode/settings.json file.
    command: /bin/echo
    buildScriptArgs: --userBuild,--workspace /u/J070188/vscode,--application environ-techleads-sandbox/src,--hlq J070188.VSCODE.USERBUILD,--outDir /u/J070188/vscode/logs
    buildScriptPath: /tmp
    additionalDependencies: application-conf
---------------------
Checking user settings...
User settings should be defined in your VS Code or Theia Settings under zopeneditor.userbuild.userSettings
    localWorkspacePath: **Optional setting is missing**
    dbbWorkspace: /u/J070188/vscode
    dbbHlq: J070188.VSCODE.USERBUILD
    dbbLogDir: /u/J070188/vscode/logs
---------------------
The default Zowe CLI profile specified as GMVS in zopeneditor.zowe setting. Will try loading that.
Using Zowe profile GMVS
An error occurred: Timed out waiting for password.
```

**Comment by phaumer** [comment]
Fixed in v2.0.3

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

I update to 2.0.3.

Sorry, but IBM User Build functions are still freezing since I upgraded to Zowe CLI V2.

The initial problem may have been solved but I can't test it (except to go back to Zowe CLI V1).

Do you want me to open a different issue to track the crash case with Zowe CLI V2?

**Comment by phaumer** [comment]
@FALLAI-Denis yes, please. Let us know how to reproduce it.

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis there is a new feature in the Zowe CLI that allows the use of home and project dir config file profiles at the same time and is why you see all available.  If the names are the same only the project level will be available of that particular name due to the precedence.  
For the prompting of credentials in Zowe Explorer, if the `autoStore: true` in config file you should only be prompted the one time and then the values are saved to the keystore and in turn will be used across both Zowe Explorer and Z Open Editor.  The issue I am seeing with the User Build is the ssh profile password.  Zowe Explorer is saving the zosmf one for you but if your config file is like the one shared in the Zowe CLI issue the ssh password is stored in it's own secure array and not shared across profiles like if using the base profile.  What you can do to store the ssh password in the keystore you can run the command while in the project directory `zowe config set --secure "profiles.host1.profiles.service2.properties.setting" "value" --user-config` changing the set path to match the config file in place and value for the password, for example using the config shared in the Zowe CLI issue should be `profiles.GMVS-SSH.properties.password`
