### ISSUE TITLE
Error Copybook xxx contains the following error : "ERROR_TOKEN" unexpected tokens ignored

### ISSUE THREAD

**Issue by YvesMichon** [IBM/zopeneditor-about#237]
With version 2.0.0 of IBM Z Open Editor, we have sometimes a message about COPYBOOKS.
![image](https://user-images.githubusercontent.com/79926253/165505113-25bb912c-fffe-4093-b5b3-a75b4bf0fb23.png)

 and on the line after the error, another error is marked : 
![image](https://user-images.githubusercontent.com/79926253/165504867-076d5f8d-4393-4a24-b190-417df230fc55.png)

When we downgrade to 1.4.1 the errors messages never appear.

The program contains multiple declarations of DB2 Tables. The message appaears just for one copybook.

## Development environment used

- Z Open Editor version: 2.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.66.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 20H2
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): openjdk version "11" 2018-09-25
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 1.26.0
  - Node.js version: 14.18.3
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes
[10-IBM Z Open Editor.log](https://github.com/IBM/zopeneditor-about/files/8571469/10-IBM.Z.Open.Editor.log)

The Copybook is here :
[TD40V2.txt](https://github.com/IBM/zopeneditor-about/files/8571401/TD40V2.txt)

**Comment by phaumer** [comment]
@YvesMichon we cannot reproduce the issue from the language server point of view. From the screen shot it looks like a timing issue, which could happen if fetching the copybook takes a bit longer, then the language server decides to time out and start parsing. As I see from the log it fails in the first data set to find it, but then finds it in the second one. The result is this underline that also has a squiggle, which mean that the program was not fully parsed since the copybook was resolved. The easiest way to resolve this is typically to just continue editing such as just typing a space then the parsing should succeed and the squiggle go away.

**Comment by YvesMichon** [comment]
HI @phaumer 
I've tried to edit the file after the error message spawned. But it was stayed. I've wait 5 minutes before editing but not better.

**Comment by PrasangAPrajapati** [comment]
Hi @YvesMichon We still can not reproduce the issue from the language server point of view. Also, wanted to follow up to see if you are still experiencing this issue after the release of 2.0.2?

If you are and if possible, could you pass along the sample COBOL program that we can test along with the given copybook? This will better help us figure out why it is giving an error.

Thanks again.

**Comment by FALLAI-Denis** [comment]
Hi,

Does the problem occurs only if it is the end point of the COBOL sentence that is in column 72? 

The true COBOL end-of-sentence sequence is the point-space sequence, with a tolerance when the point is in column 72 and in this case the space after point is optional. 

The COBOL language server may not Well handle this tolerance.

**Comment by FALLAI-Denis** [comment]
Hi, 

I reproduced the problem of @YvesMichon:

![image](https://user-images.githubusercontent.com/63861965/169589970-d8400dd6-c07f-4d6c-b294-5559f8214047.png)

It occurs when replacing does not find a match in the COPYBOOK. 
In my case because the cache contained an outdated version of the COPYBOOK: a reload of VS Code solved the problem (clearing the COPYBOOKs cache).

See if this option of Zowe Explorer is active in the configuration of @YvesMichon:

![image](https://user-images.githubusercontent.com/63861965/169591093-8f3ec1f0-8dd3-469d-9580-8ec1ccc0e9cc.png)

**Comment by PrasangAPrajapati** [comment]
@YvesMichon @AlexKotsc We still can not reproduce the issue from the language server point of view. Also, wanted to follow up to see if you are still experiencing this issue.

If you are and if possible, could you pass along the sample COBOL program that we can test along with the given copybook? This will better help us figure out why it is giving an error.

Thanks again.

**Comment by YvesMichon** [comment]
Hi @PrasangAPrajapati  

Here is a case. It's the program DGI410.
You'll find in the zip the source and the COPY files. The COPY files are in a folders that I retrieved from C:\Users\<Myuser>\.vscode\extensions\ibm.zopeneditor-2.2.0\resources\temp\_D_\zosmf\E$DTA.$RSRCTES.COPY
You'll find too the IBM Z Openeditor Log when the program was loaded.

I've tested by putting all copy in the same folder as the program instead of searching them on Mainframe, and there is no errors.
But when copy files are coming from mainframe the errors pops.
![image](https://user-images.githubusercontent.com/79926253/196382414-48000926-30a1-48b1-92d1-fc944d7500a6.png)
![image](https://user-images.githubusercontent.com/79926253/196382477-f9acbb09-e974-4958-83ab-899fba171ef5.png)
[DGI410.zip](https://github.com/IBM/zopeneditor-about/files/9808573/DGI410.zip)
[log.txt](https://github.com/IBM/zopeneditor-about/files/9808576/log.txt)

**Comment by dakaa16** [comment]
Hi @PrasangAPrajapati and @YvesMichon. This problem seems to be resolved in Z Open Editor version 3.0.0. We've had the problem since we started using Z Open Editor, but as we updated to version 3, the errors shown for the copybooks in the source module are gone. Note we currently have a mix, where some copybooks are found locally on the machine, and some are fetched from the mainframe. Both of the methods of loading in copybooks have been successful in all the tests we've made.

**Comment by PrasangAPrajapati** [comment]
Thanks, @dakaa16 for verifying. Yes, the issue has been fixed and resolved. Feel free to re-open the issue or file a new one if you get any issues.

**Comment by YvesMichon** [comment]
Hi @dakaa16 & @PrasangAPrajapati !

Sorry. But I've still have the problem qith my program DGI410 as shown above with version 3.0.0 of IBMZ Z Open Editor.

**Comment by YvesMichon** [comment]
Hi @sdaimwood 
The issue seems now to be resolved with my actual 3.1.1 version of IBM Z open Editor.
Thanks for all.

**Comment by sdaimwood** [comment]
> Hi @sdaimwood
> The issue seems now to be resolved with my actual 3.1.1 version of IBM Z open Editor.
> Thanks for all.

Glad to hear! We’ll close this issue out then.
