### ISSUE TITLE
COBOL - Minor issues with literal delimiters in the COBOL textmate grammar

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#308]
## Development environment used

- Z Open Editor version: 3.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.74.2
- Operating System: Windows 10
- Java Version: 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

Minor bugs in the handling of literal delimiters.

Some delimiters are not correctly recognized:
* those using the apostrophe character
* some prefixes

The issues are related to the textmate grammar associated with the COBOL language.

```
      "begin": "\"",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\"|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.double.cobol"
    },
    {
      "begin": "'",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "('|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.single.cobol"
    },
    {
      "begin": "([zZ]|[nN]|[uU])\"",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\"|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.double.cobol"
    },
```

### Observed behavior

![image](https://user-images.githubusercontent.com/63861965/208982644-2bfc14ef-9fb2-4050-9187-4ab978f8e804.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/63861965/208985644-e7938646-05da-4244-9e9a-53dbd4639405.png)

I propose a simplification along with a correction:

```
    {
      "begin": "(?:[nNuU]?[xX]|[gGnNuUzZ])?(\")",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\\1|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.double.cobol"
    },
    {
      "begin": "(?:[nNuU]?[xX]|[gGnNuUzZ])?(')",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\\1|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.single.cobol"
    },
```

or only:

```
    {
      "begin": "(?:[nNuU]?[xX]|[gGnNuUzZ])?([\"'])",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\\1|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.cobol"
    },
```

**Comment by phaumer** [comment]
Thanks! Happy holidays!

**Comment by FALLAI-Denis** [comment]
Hi,

The ZOE COBOL grammar also includes the following rules which are not legal for the IBM Enterprise COBOL compiler:

```
    {
      "match": "([hH])'\\h*'",
      "name": "constant.numeric.integer.hexadecimal.cobol"
    },
    {
      "match": "([hH])'.*'",
      "name": "invalid.illegal.hexadecimal.cobol"
    },
    {
      "match": "([hH])\"\\h*\"",
      "name": "constant.numeric.integer.hexadecimal.cobol"
    },
    {
      "match": "([hH])\".*\"",
      "name": "invalid.illegal.hexadecimal.cobol"
    },
    {
      "match": "[oO]\"[0-7]*\"",
      "name": "constant.numeric.integer.octal.cobol"
    },
    {
      "match": "[oO]\".*\"",
      "name": "invalid.illegal.octal.cobol"
    },
```

**Comment by phaumer** [comment]
In 3.0.1 we only fixed the textmate. The Language Server fix will be in a future release.

**Comment by FALLAI-Denis** [comment]
Hi,

New rule in ZOE 3.0.1 :

```
    {
      "begin": "([bBnNuU]?[xX]|[bBgGnNuUzZ])?([\"'])",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "([\"']|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.cobol"
    },
```

The end part should match the begin part about quote or apostrophe: I suggest to use in end part a referback to begin part.

    {
      "begin": "(?:[bBnNuU]?[xX]|[bBgGnNuUzZ])?([\"'])",
      "beginCaptures": {
        "0": {
          "name": "punctuation.definition.string.begin.cobol"
        }
      },
      "end": "(\\1)|$)",
      "endCaptures": {
        "0": {
          "name": "punctuation.definition.string.end.cobol"
        }
      },
      "name": "string.quoted.cobol"
    },

**Comment by phaumer** [comment]
Fixed some of these in Z Open Editor 3.1.0. Some items listed are not support yet by IBM COBOL compiler.

**Comment by FALLAI-Denis** [comment]
Sorry but still wrong for ending delimiter wich must match opening delimiter with a referback.

![image](https://user-images.githubusercontent.com/63861965/224491701-b7175f1f-feb2-4cb2-b8ff-1c91bc1cd79f.png)

**Comment by FALLAI-Denis** [comment]
Hi @phaumer 

I suggest to reopen this issue.

**Comment by sdaimwood** [comment]
Hi @FALLAI-Denis,

Thank you for the contributions here, we intend to fix that textmate error with the nested double quote or single quote. 

However for the `b` and `bx` tokens, we reverted that change intentionally as we spoke with the IBM COBOL compiler team and they informed us that although that syntax is a part of the COBOL ISO Standard, the IBM COBOL on Z compiler does not support it. Our intention with the parser and syntax highlighting is to match as closely as possible to the IBM compiler so users are able to see the error prior to compiling.

**Comment by FALLAI-Denis** [comment]
Hi,

Ok for `b` an `bx`. I hope boolean format will soon be available in IBM Enterprise COBOL compiler.

Perhaps same for `-` continuation delimiter at end of string.

The textmate rule would then be:

```
        {
          "begin": "(?:[nNuU]?[xX]|[gGnNuUzZ])?([\"'])",
          "beginCaptures": {
            "0": {
              "name": "punctuation.definition.string.begin.cobol"
            }
          },
          "end": "\\1|$",
          "endCaptures": {
            "0": {
              "name": "punctuation.definition.string.end.cobol"
            }
          },
          "name": "string.quoted.cobol"
        },
```

**Comment by phaumer** [comment]
Made the updates discussed in v3.1.1.
