### ISSUE TITLE
VSCODE encoding error IBM-1208 since 3.1.0 update

### ISSUE THREAD

**Issue by rsjrny** [IBM/zopeneditor-about#331]
### Discussed in https://github.com/IBM/zopeneditor-about/discussions/330

<div type='discussions-op-text'>

<sup>Originally posted by **rsjrny** March 11, 2023</sup>
since the extension update 3.1.0 on 3/10/23 I have started receiving an encoding issue with CopyToPDS in groovy. If I initiate the same user build directly from USS the CopyToPDS works fine. I assume it has something to do with the transfer from windows to USS.

I am at a loss as to where to start looking for a possible setting change. any help would be appreciated

```
2023-03-11T11:06:46.416Z: Caught: com.ibm.dbb.build.BuildException: java.io.UnsupportedEncodingException: ibm-1208
2023-03-11T11:06:46.421Z: com.ibm.dbb.build.BuildException: java.io.UnsupportedEncodingException: ibm-1208
2023-03-11T11:06:46.426Z: at com.ibm.dbb.build.CopyToPDS.execute(CopyToPDS.java:89)
2023-03-11T11:06:46.429Z: at BuildUtilities.copySourceFiles(BuildUtilities.groovy:100)
2023-03-11T11:06:46.432Z: at Assembler$_run_closure1.doCall(Assembler.groovy:36)
2023-03-11T11:06:46.438Z: at Assembler.run(Assembler.groovy:28)
2023-03-11T11:06:46.443Z: at Assembler$run.callCurrent(Unknown Source)
2023-03-11T11:06:46.445Z: at com.ibm.dbb.groovy.ScriptLoader._run(ScriptLoader.groovy:124)
2023-03-11T11:06:46.448Z: at com.ibm.dbb.groovy.ScriptLoader$_run$0.call(Unknown Source)
2023-03-11T11:06:46.458Z: at com.ibm.dbb.groovy.ScriptLoader.runScript(ScriptLoader.groovy:81)
2023-03-11T11:06:46.461Z: at build$_run_closure1.doCall(build.groovy:63)
2023-03-11T11:06:46.464Z: at build.run(build.groovy:54)
2023-03-11T11:06:46.467Z: Caused by: java.io.UnsupportedEncodingException: ibm-1208
2023-03-11T11:06:46.472Z: at com.ibm.dbb.build.CopyToPDS.copyAsText(CopyToPDS.java:379)
2023-03-11T11:06:46.476Z: at com.ibm.dbb.build.CopyToPDS.copyAsText(CopyToPDS.java:306)
2023-03-11T11:06:46.478Z: at com.ibm.dbb.build.CopyToPDS.copyFile(CopyToPDS.java:232)
2023-03-11T11:06:46.481Z: at com.ibm.dbb.build.CopyToPDS.doCopy(CopyToPDS.java:179)
2023-03-11T11:06:46.490Z: at com.ibm.dbb.build.CopyToPDS.execute(CopyToPDS.java:85)
```</div>

**Comment by phaumer** [comment]
It looks like that there is a regression that it will use utf-8 when no .gitattributes file is found instead of the encoding specified for the profile. As a workaround create a .gitattributes file with the encoding you need: https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.4?topic=code-setting-up-user-build

**Comment by FALLAI-Denis** [comment]
Hi,

Same problem for me... 

I do have a .gitattributes file, which states that by default files are encoded on the remote system in EBCDIC-1147; it does not specify anything for COBOL files (*.cbl) since it is the default that applies.

Even by explicitly forcing the *.cbl pattern, the files are still transferred in UTF-8...

```
# Les fichiers sont gérés et édités en UTF-8 ; sur z/OS, sauf contre indication, ils sont encodés en EBCDIC IBM-1147
*          text        working-tree-encoding=utf-8     zos-working-tree-encoding=ibm-1147
*.clb      text        working-tree-encoding=utf-8     zos-working-tree-encoding=ibm-1147
*.groovy                                               zos-working-tree-encoding=ibm-1047
*.json                                                 zos-working-tree-encoding=utf-8
*.md                                                   zos-working-tree-encoding=utf-8
*.properties                                           zos-working-tree-encoding=ibm-1047
*.rexx                                                 zos-working-tree-encoding=ibm-037
*.sh                                                   zos-working-tree-encoding=ibm-1047

# Les fichiers de configuration Zowe en utf-8 et eol=lf
zowe.*          eol=lf working-tree-encoding=utf-8     zos-working-tree-encoding=utf-8

# Les fichiers de gestion Git sont gérés en ISO-8859-1 partout
.git/                  working-tree-encoding=iso8859-1 zos-working-tree-encoding=iso8859-1
*.gitattributes eol=lf working-tree-encoding=iso8859-1 zos-working-tree-encoding=iso8859-1
*.zosattributes eol=lf working-tree-encoding=iso8859-1 zos-working-tree-encoding=iso8859-1
*.gitignore     eol=lf working-tree-encoding=iso8859-1 zos-working-tree-encoding=iso8859-1

# Types Endevor binaires
*.load      binary
*.dbrm      binary
*.objet     binary
*.objetc    binary

# Fichiers bureautique
*.ppt*     binary
*.doc*     binary
*.xls*     binary
*.pdf      binary

# Images
*.png      binary
*.gif      binary
*.jpg      binary
*.jpeg     binary
*.bmp      binary
*.ico      binary
```



```
2023-03-13T20:28:37.546Z: =====================
2023-03-13T20:28:37.548Z: Running User Build...
2023-03-13T20:28:37.550Z: Identified the local root workspace path as c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2
2023-03-13T20:28:37.553Z: ---------------------
2023-03-13T20:28:37.559Z: Checking dbb profile settings defined in your repository's zapp.yaml or zapp.json
2023-03-13T20:28:37.562Z: User setting dbbDefaultZappProfile: **dbb-userbuild**
2023-03-13T20:28:37.564Z: Will read settings from ZAPP profile called dbb-userbuild defined in User Settings
2023-03-13T20:28:37.566Z:     application: CEAB3.MVP2
    command: $DBB_HOME/bin/groovyz
    buildScriptArgs: --userBuild,--workspace /u/J070188/dbb,--application CEAB3.MVP2,--hlq J070188.DBB.CEAB3.MVP2,--outDir /u/J070188/dbb/logs
    buildScriptPath: /var/DBB/PROD/SCRIPTS/buildBPCE.groovy
    additionalDependencies: application-conf,.build,src\**\S9TL1A.cbl.build
    logFilePatterns: S9TL1A*.log,BuildReport.*
2023-03-13T20:28:37.568Z: ---------------------
2023-03-13T20:28:37.570Z: Checking user settings...
2023-03-13T20:28:37.572Z: User settings should be defined in your VS Code or Theia Settings under zopeneditor.userbuild.userSettings
2023-03-13T20:28:37.574Z:     dbbWorkspace: /u/J070188/dbb
    dbbHlq: J070188.DBB
    dbbLogDir: /u/J070188/dbb/logs
    dbbDefaultZappProfile: dbb-userbuild
    localLogDir: .reports
2023-03-13T20:28:37.576Z: Using .gitattributes file at c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.gitattributes
2023-03-13T20:28:37.578Z: ---------------------
2023-03-13T20:28:37.580Z: The default Zowe CLI profile specified as TMVS in zopeneditor.zowe setting. Will try loading that.
2023-03-13T20:28:37.583Z: Using Zowe profile TMVS
2023-03-13T20:28:37.879Z: Using ssh profile TMVS-SSH
2023-03-13T20:28:37.882Z: 
2023-03-13T20:28:37.883Z: Checking if SSH profile TMVS-SSH can connect:
2023-03-13T20:28:38.305Z: Connected successfully.
2023-03-13T20:28:38.307Z: 
2023-03-13T20:28:38.528Z: Executing SSH command: 
mkdir -p '/u/J070188/dbb/CEAB3.MVP2/src/COBOL'
2023-03-13T20:28:38.911Z: @@START OF COMMAND@@
2023-03-13T20:28:38.914Z: $ mkdir -p '/u/J070188/dbb/CEAB3.MVP2/src/COBOL'
2023-03-13T20:28:38.915Z: $ exit $?
2023-03-13T20:28:38.922Z: No encoding found for *S9TL1A.cbl. Assigning default encoding of utf-8
2023-03-13T20:28:38.924Z: Uploading file c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\src\COBOL\S9TL1A.cbl to /u/J070188/dbb/CEAB3.MVP2/src/COBOL/S9TL1A.cbl with encoding utf-8
2023-03-13T20:28:39.217Z: Using ssh profile TMVS-SSH
2023-03-13T20:28:39.218Z: Executing SSH command: 
chtag -tc utf-8 '/u/J070188/dbb/CEAB3.MVP2/src/COBOL/S9TL1A.cbl'
2023-03-13T20:28:39.594Z: @@START OF COMMAND@@
2023-03-13T20:28:39.596Z: $ chtag -tc utf-8 '/u/J070188/dbb/CEAB3.MVP2/src/COBOL/S9TL1A.cbl'
2023-03-13T20:28:39.608Z: $ exit $?
2023-03-13T20:28:39.612Z: Fetching build file dependencies...
2023-03-13T20:28:43.571Z: Found a total of 23 local include files:
2023-03-13T20:28:43.572Z: c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.imports\GCL\src\bloc\application\domaine\COPYCOB\SGFDAPP.cpy
2023-03-13T20:28:43.574Z: c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.imports\GCL\src\bloc\application\domaine\COPYCOB\SGFDADM.cpy
2023-03-13T20:28:43.575Z: c:\Users\S0070188\.vscodeMainframe\ibm.zopeneditor-3.1.0\resources\temp\_D_\TMVS\DSGETU.PERMIBL.SIRIS.COPY\AAA5LSNN.cpy
```

**Comment by FALLAI-Denis** [comment]
Check attribute:

```
S0070188@O0IC3071 MINGW64 /c/Trv/DepotsGIT/ceab3-environn-outinfr-central-mvp2/src/COBOL (develop)
$ git check-attr -a S9TL1A.cbl
S9TL1A.cbl: text: set
S9TL1A.cbl: working-tree-encoding: utf-8       
S9TL1A.cbl: zos-working-tree-encoding: ibm-1147
```

Does ZOE use the zos-working-tree-encoding declaration correctly?

Confer change in ZOE 3.1.0:

- Added support for path name specification for .gitattributes in IBM User Build.
- Added **new option for tagging files using working-tree-encoding os=zos in .gitattributes** in IBM User Build as an alternative to zos-working-tree-encoding.

**Comment by FALLAI-Denis** [comment]
Hi,

@phaumer remember #236 

Thanks.

**Comment by phaumer** [comment]
@FALLAI-Denis I do not disagree. Our original requirement was to use this file even when the user does not have git installed locally (e.g. they got the repo by downloading it as a zip from github), but I agree it might be worth supporting both type of checks.

**Comment by FALLAI-Denis** [comment]
Hi @phaumer,

In my opinion, if there is a .gitattributes file present in the Workspace, it means that we are probably in the presence of a Git Repository, and therefore that Git must be available in the working context of VS Code and therefore from Z Open Editor.

Moreover the IBM User Build function of Z Open Editor is mainly intended to work with zAppbuild, itself intended to work with IBM Dependency Based Build, and zAppbuild is still well built to work with Git, (and I even wonder if IBM DBB itself isn't built to work with Git, but that's less obvious).

So I think it's complicating your life to want Z Open Editor to do its own Git-style attribute management...
Either Git is available and then you have to call the git check-attr command.
Either Git is not available and then you have to use the encoding declared by the z/OSMF profile, or the zapp property groups for the RSE profile.

**Comment by phaumer** [comment]
We fixed the regressions for `*` and falling back to the Zowe profiles settings in case no match was found in v3.1.1 @rsjrny. 
Using the git command we treat as a separate enhancement request.

**Comment by rsjrny** [comment]
@phaumer 
I am still seeing the error after upgrading to Z Open Editor 3.1.1

`2023-03-30T17:12:27.433Z: ** Build start at 20230330.011227.012
2023-03-30T17:12:28.113Z: Caught: java.io.UnsupportedEncodingException: ibm-1208
2023-03-30T17:12:28.115Z: java.io.UnsupportedEncodingException: ibm-1208
2023-03-30T17:12:28.116Z: at com.ibm.dbb.build.BuildProperties.loadProperties(BuildProperties.java:202)
2023-03-30T17:12:28.117Z: at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:161)
2023-03-30T17:12:28.118Z: at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:149)
2023-03-30T17:12:28.120Z: at build$_populateBuildProperties_closure4.doCall(build.groovy:376)
2023-03-30T17:12:28.121Z: at build.populateBuildProperties(build.groovy:371)
2023-03-30T17:12:28.124Z: at build.initializeBuildProcess(build.groovy:97)
2023-03-30T17:12:28.126Z: at build.run(build.groovy:32)
2023-03-30T17:12:28.921Z: ** Build finished`

**Comment by rsjrny** [comment]
I had changed it to the following. It is in the top level
.gitattributes zos-working-tree-encoding=iso8859-1
.gitignore     zos-working-tree-encoding=iso8859-1
*.c            text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.h            text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.maclib       text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.samplib      text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.srclib       text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.prelink      text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.log          text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
*.cntlrep      binary
*.isptlib      binary

**Comment by rsjrny** [comment]
whoops,  forgot to copy the last line

*              text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047

**Comment by rudyflores** [comment]
Hey @rsjrny ! When running a User Build with the following `.gitattributes` file you provided:
```.gitattributes
*              text working-tree-encoding=utf-8      zos-working-tree-encoding=ibm-1047
.gitattributes zos-working-tree-encoding=iso8859-1
.gitignore zos-working-tree-encoding=iso8859-1
*.c text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.h text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.maclib text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.samplib text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.srclib text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.prelink text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.log text working-tree-encoding=utf-8 zos-working-tree-encoding=ibm-1047
*.cntlrep binary
*.isptlib binary
```

What is the expected encoding? I see `IBM-1208` is being applied which I assume is the default on your z/OS machine?

**Comment by rsjrny** [comment]
@phaumer 

it is expecting IBM-1047
I issued ls -aLT thminit.srclib in the build directory and this is what I see
t IBM-1047    T=on  thminit.srclib 

if I initiate the build on USS I have no issues. The problem only occurs when the build is initiated from VSCode

here is the vscode log

`2023-03-31T16:43:18.580Z: Using .gitattributes file at c:\Repos\TMON\tmon-18926rl-tmhmv010\.gitattributes
2023-03-31T16:43:18.581Z: ---------------------
2023-03-31T16:43:18.585Z: The default Zowe CLI profile specified as RSI2 in zopeneditor.zowe setting. Will try loading that.
2023-03-31T16:43:18.587Z: Using Zowe profile RSI2
2023-03-31T16:43:18.971Z: Using ssh profile rsi2ssh
2023-03-31T16:43:18.972Z: 
2023-03-31T16:43:18.973Z: Checking if SSH profile rsi2ssh can connect:
2023-03-31T16:43:19.484Z: Connected successfully.
2023-03-31T16:43:19.485Z: 
2023-03-31T16:43:19.769Z: Executing SSH command: 
mkdir -p '/u/ts4579/build/tmhmv010'
2023-03-31T16:43:20.400Z: @@START OF COMMAND@@
2023-03-31T16:43:20.402Z: $ mkdir -p '/u/ts4579/build/tmhmv010'
2023-03-31T16:43:20.411Z: Uploading file c:\Repos\TMON\tmon-18926rl-tmhmv010\thminit.srclib to /u/ts4579/build/tmhmv010/thminit.srclib with encoding ibm-1047
2023-03-31T16:43:20.820Z: Using ssh profile rsi2ssh
2023-03-31T16:43:20.822Z: Executing SSH command: 
chtag -tc ibm-1047 '/u/ts4579/build/tmhmv010/thminit.srclib'
2023-03-31T16:43:21.458Z: $ chtag -tc ibm-1047 '/u/ts4579/build/tmhmv010/thminit.srclib'
2023-03-31T16:43:21.480Z: Fetching build file dependencies...
2023-03-31T16:43:24.389Z: Found a total of 0 local include files:
2023-03-31T16:43:24.390Z: Checking if include files were updated since the last build...
2023-03-31T16:43:24.391Z: Updating 0/0 local include files.
2023-03-31T16:43:24.393Z: ---------------------
2023-03-31T16:43:24.697Z: Executing SSH command: 
$DBB_HOME/bin/groovyz /u/prodpc2/dbb-zappbuild-rsjrny/build.groovy     --userBuild    --workspace /u/ts4579/build/ --application tmhmv010 --hlq TMHMV010.U18926RL --outDir /u/ts4579/dbbuild/tmhmv010/logs --propFiles /u/ts4579/build/tmhmv010/procgrpList.properties --prodver tmhmv010    '/u/ts4579/build/tmhmv010/thminit.srclib'
2023-03-31T16:43:25.331Z: $ $DBB_HOME/bin/groovyz /u/prodpc2/dbb-zappbuild-rsjrny/build.groovy     --use
$
2023-03-31T16:43:25.339Z: $ zappbuild-rsjrny/build.groovy     --user                                    <Build    --workspace /u/ts4579/build
$
2023-03-31T16:43:25.343Z: $ serBuild    --workspace /u/ts4579/build/                                    < --application tmhmv010 --hlq TMHMV0
$
2023-03-31T16:43:25.348Z: $ ld/ --application tmhmv010 --hlq TMHMV01                                    <0.U18926RL --outDir /u/ts4579/dbbuil
$
2023-03-31T16:43:25.350Z: $ V010.U18926RL --outDir /u/ts4579/dbbuild                                    </tmhmv010/logs --propFiles /u/ts4579
$
2023-03-31T16:43:25.358Z: $ ild/tmhmv010/logs --propFiles /u/ts4579/                                    <build/tmhmv010/procgrpList.propertie
$
2023-03-31T16:43:25.361Z: $ 79/build/tmhmv010/procgrpList.properties                                    < --prodver tmhmv010    '/u/ts4579/bu
$
2023-03-31T16:43:25.365Z: $ ies --prodver tmhmv010    '/u/ts4579/bui                                    <ld/tmhmv010/thminit.srclib'
2023-03-31T16:43:32.267Z: ** Build start at 20230331.124332.043
2023-03-31T16:43:32.463Z: Caught: java.io.UnsupportedEncodingException: ibm-1208
2023-03-31T16:43:32.466Z: java.io.UnsupportedEncodingException: ibm-1208
2023-03-31T16:43:32.468Z: at com.ibm.dbb.build.BuildProperties.loadProperties(BuildProperties.java:202)
2023-03-31T16:43:32.470Z: at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:161)
	at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:149)
2023-03-31T16:43:32.472Z: at build$_populateBuildProperties_closure4.doCall(build.groovy:374)
2023-03-31T16:43:32.478Z: at build.populateBuildProperties(build.groovy:369)
2023-03-31T16:43:32.483Z: at build.initializeBuildProcess(build.groovy:94)
2023-03-31T16:43:32.486Z: at build.run(build.groovy:32)
2023-03-31T16:43:33.170Z: ** Build finished
2023-03-31T16:43:33.185Z: An error has occurred: Error: Something went wrong executing SSH command $DBB_HOME/bin/groovyz /u/prodpc2/dbb-zappbuild-rsjrny/build.groovy     --userBuild    --workspace /u/ts4579/build/ --application tmhmv010 --hlq TMHMV010.U18926RL --outDir /u/ts4579/dbbuild/tmhmv010/logs --propFiles /u/ts4579/build/tmhmv010/procgrpList.properties --prodver tmhmv010    '/u/ts4579/build/tmhmv010/thminit.srclib'
2023-03-31T16:43:33.187Z: Looking for user build logs in "/u/ts4579/dbbuild/tmhmv010/logs".
2023-03-31T16:43:33.189Z: Total log files found: 0
2023-03-31T16:43:33.190Z: Downloading logs to c:\Repos\TMON\tmon-18926rl-tmhmv010\logs
2023-03-31T16:43:33.191Z: Successfully finished downloading of 0 log files to c:\Repos\TMON\tmon-18926rl-tmhmv010\logs.`

**Comment by FALLAI-Denis** [comment]
Hi @rsjrny ,

I analyzed your IBM User Build log: a priori the file `thminit.srclib` is transferred as IBM-1047 and tagged as IBM-1047.

`2023-03-31T16:43:20.411Z: Uploading file c:\Repos\TMON\tmon-18926rl-tmhmv010\thminit.srclib to u/ts4579/build/tmhmv010/thminit.srclib with encoding ibm-1047`

`2023-03-31T16:43:21.458Z: $ chtag -tc ibm-1047 '/u/ts4579/build/tmhmv010/thminit.srclib'`

The problem could come from another file already present in the user build workspace on USS...

```
2023-03-31T16:43:32.463Z: Caught: java.io.UnsupportedEncodingException: ibm-1208
2023-03-31T16:43:32.466Z: java.io.UnsupportedEncodingException: ibm-1208
2023-03-31T16:43:32.468Z: at com.ibm.dbb.build.BuildProperties.loadProperties(BuildProperties.java:202)
2023-03-31T16:43:32.470Z: at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:161)
                          at com.ibm.dbb.build.BuildProperties.load(BuildProperties.java:149)
2023-03-31T16:43:32.472Z: at build$_populateBuildProperties_closure4.doCall(build.groovy:374)
2023-03-31T16:43:32.478Z: at build.populateBuildProperties(build.groovy:369)
2023-03-31T16:43:32.483Z: at build.initializeBuildProcess(build.groovy:94)
2023-03-31T16:43:32.486Z: at build.run(build.groovy:32)
```

It could be a properties file: `loadProperties` function in Java exception message.
Did you re-setup the user build  workspace before starting the user build itself?

**Comment by rsjrny** [comment]
@FALLAI-Denis,

That was the issue, you nailed it.
I deleted the build workspace, ran user build setup, then the userbuild.

all is well.

thanks!

**Comment by phaumer** [comment]
Great to hear. Thanks for the help @FALLAI-Denis.

**Comment by phaumer** [comment]
We added the ability to utilize the `git check-attr` command in the background to evaluate `.gitattributes` in Z Open Editor 3.2.0. If our code can find the command in the path it will use it, otherwise fall back to our previous algorithm.
