### ISSUE TITLE
COBOL - ZOE does not immediately display a clickable link on copybook references (since ZOE 3.3.2)

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#371]
## Development environment used

- Z Open Editor version: 3.3.2
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.84.2
- Operating System: Windows 10 21H2
- Java Version: 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: no

## Problem Description

I have noticed strange behavior from ZOE since version 3.3.2 (or since VS Code version 1.84.2?) in the management of copybooks:
* The reference to the copybook is not underlined and therefore is not a clickable link.
* However, hovering over the reference to the copybook displays the content of the copybook, but there is no “Ctrl-click to open” information.
* In the ZOE log we see that the copybook was found.

In fact it seems that the clickable links on the references to cobybooks appear after opening and closing another editor or another window in the main VS Code panel.

### Observed behavior

Open zip file to see screen capture.
[timetogetlink.zip](https://github.com/IBM/zopeneditor-about/files/13568045/timetogetlink.zip)

**Comment by sdaimwood** [comment]
Hi @FALLAI-Denis, thanks for reporting this and attaching the video. If you're able to reproduce this consistently could you attach the language server log after the scenario you recorded? That should help narrow down if it is something in the servers causing the links to not appear or if it's on the client side.

**Comment by FALLAI-Denis** [comment]
Hi @sdaimwood,

No "language server COBOL" log produced... (or not found?).

Opening and closing any other file (not COBOL), or switching from editor to other, activate links on copybooks.

Found some logs relate to ZOE:
[renderer.log](https://github.com/IBM/zopeneditor-about/files/13587825/renderer.log)
[exthost.log](https://github.com/IBM/zopeneditor-about/files/13587834/exthost.log)
[zopeneditor-20231206-151450.log](https://github.com/IBM/zopeneditor-about/files/13587840/zopeneditor-20231206-151450.log)
[userbuild-20231206-151451.log](https://github.com/IBM/zopeneditor-about/files/13587842/userbuild-20231206-151451.log)

The tests were carried out with the zipfile provided for issue #366: 
* #366
But the problem is reproducible on other workspaces.

**Comment by sdaimwood** [comment]
Hi @FALLAI-Denis, sorry for the delay replying. When there is no "COBOL language server" output produced in VSCode you can find the language trace by doing the following: 

Enable Debug level for the Z Open Editor log(`zopeneditor.logger` in preferences), once enabled, open a COBOL file as normal and search in the Z Open Editor log for "-data". You should see the string in the startup command for the COBOL language server and immediately following the -data should be a folder location. This contains a `.log` file for the language server trace. Could you attach that file? 

Here's a screenshot illustrating what you should see when searching for the log folder:

<img width="1259" alt="Screenshot 2023-12-11 at 3 53 41 PM" src="https://github.com/IBM/zopeneditor-about/assets/93732205/bf782b8d-184e-432c-8f6e-e6fbdcc77f59">

On mac the folder structure should be similar, on Windows it should be located in a tmp directory, most likely in AppData. In that folder, go into `.metadata`, and attach the `.log` file (not the `.trace` if it's present).

**Comment by FALLAI-Denis** [comment]
Hi @sdaimwood 

I found a `.metadata` folder, and a `.log` file inside :
[metadata.zip](https://github.com/IBM/zopeneditor-about/files/13641194/metadata.zip)

The corresponding ZOE log:
[zopeneditor-20231211-212634.log](https://github.com/IBM/zopeneditor-about/files/13641225/zopeneditor-20231211-212634.log)

I open a first cobol file at `2023-12-11 22:26:41.719` (?)
--> no clickable link
I open a second cobol file (empty, no copybook) and close it immediately at `2023-12-11 22:32:51.717` (?)
--> clickable link on first cobol file

**Comment by sdaimwood** [comment]
Thank you @FALLAI-Denis, both of those logs are helpful. I'm having difficulty reproducing locally but will continue to try with different environments. We have seen this issue intermittently with all of the language servers but it's odd that you're seeing the issue again after updating to 3.3.2.

**Comment by FALLAI-Denis** [comment]
Hi,

I carried out some tests:
* typing in the editor affected by the link display problem causes the links to appear
* use of the same use case on several computers (all Windows) --> same problem
* creation of a VS Code profile only activating the ZOE and Zowe Explorer extensions, same use case --> same problem
* creation of a use case with copybooks without conditional compilation --> no more problems!

The problem does not seem linked to the extensions used but only linked to the copybooks used: if certain copybooks contain conditional compilation directives then no link appears immediately, even on copybooks not containing a conditional compilation directive, but only after a refreshing the editor containing the source text.

I also noticed that Z Open Editor was looking for copybooks normally excluded by conditional compilation, and depending on how zapp.yaml is configured, these copybooks may not be found.
Problem seen in the use case provided for issue #366 with a copybook search only locally: the copybooks A2ADTIAR, A2APTIAR, AAA5LSNN and AAADVSTA are searched, although excluded by the conditional compilation, and not found because they do not exist local.

I think that at the Language Server level there is a competition between the copybook search process and the conditional compilation processing process, and a synchronization problem between these two processes.

**Comment by FALLAI-Denis** [comment]
Hi,

In attachement a new simplified use case.

[ZOE371.zip](https://github.com/IBM/zopeneditor-about/files/13704034/ZOE371.zip)

**Comment by sdaimwood** [comment]
Hi @FALLAI-Denis,

Thank you for providing the sample and additional diagnostic information, it's very helpful. 

With the extra information and the sample files, I was able to reproduce consistently on Windows. Oddly enough and adding to the difficulty in diagnosing, everything works as expected on MacOS when opening the sample. 

https://github.com/IBM/zopeneditor-about/assets/93732205/6880811c-09ff-47b7-8aba-c14aeb09559d

That could mean it's an issue with LSP4J, but will look into it further to determine. Narrowing it down to copybooks with CC will help a great deal in finding a solution if it's possible, so thank you again. Will keep you updated on progress for this item.

**Comment by sdaimwood** [comment]
Hi @FALLAI-Denis, could you check if this issue is alleviated for you? With the sample you've provided I believe a fix for this was actually shipped in 3.4.0 when we fixed #363. Everything seems to be working as expected when opening the sample you've provided on both Mac and Windows now.

**Comment by FALLAI-Denis** [comment]
Hi @sdaimwood,

Sorry but problem still present for me... still in same conditions...
* OS: Windows 10 22H2
* VS Code: 1.87.2
* IBM Z Open Editor: 4.1.0
* Java runtime: 17.0.9+9 (forced in `zopeneditor.JAVA_HOME: c:\\trv\\install\\modules java UdD-M\\jdk-17.0.9+9-jre`)

Forced version:
```
c:\Trv\install\modules java UdD-M\jdk-17.0.9+9-jre\bin>java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
```
Default version:
```
c:\>java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```
