### ISSUE TITLE
After upgrade to 5.2, no symbols found

### ISSUE THREAD

**Issue by johntgatesjr** [IBM/zopeneditor-about#487]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:  1.97.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  MAC/OS 15.3.1
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
-java --version
openjdk 17.0.8.1 2023-08-24
IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
Eclipse OpenJ9 VM 17.0.8.1 (build openj9-0.40.0, JRE 17 Mac OS X aarch64-64-Bit 20230824_392 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 8ecf238a124 based on jdk-17.0.8.1+1)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

Problem:
After upgrading to Open Editor 5.2, symbols are no longer loaded when I open a PDS member.  We use the Outline view extensively and it uses symbols.

-

**Comment by johntgatesjr** [comment]
Note we are using HLASM and JCL.  We use Outline view for our ASM and MACLIB parts.  This worked correctly in 5.1.  Also, opening some parts seems to load symbols properly ?  While most do not.

**Comment by sdaimwood** [comment]
Thank you for reporting this issue @johntgatesjr. Are you seeing it only when PDS members are opened or also in local files with the same content? 

If possible, could you provide a sample file where you're seeing the issue occurring?

**Comment by johntgatesjr** [comment]
All of our code is in PDS's so the answer is only in PDS's.  I open a PDS member.  Where the symbols used to get loaded and populate the Outline view, with 5.2, the symbols fail to load and the Outline view is blank.  When we revert back to a 5.1 version, all works as before and the symbols are loaded properly.

**Comment by sdaimwood** [comment]
Would it be possible to provide a code sample where you're seeing the outline view failures @johntgatesjr?

**Comment by johntgatesjr** [comment]
It happens with all of our parts.  We use a lot of macros.  Without sending you an entire PDS, it's not likely a code sample would be helpful.

**Comment by johntgatesjr** [comment]
I think we're getting to the bottom of this.

- We were running 5.0.
- We upgraded to 5.1 with no issues.
- We upgraded to 5.2, primarily to get Hover working for private maclibs on the z/OS system.  This was OOB functionality with RDz and something that has always been missing from IBM z Editor.
- After moving to 5.2 we encountered symbol problems that prevented Outline view from working properly.
- We moved back to 5.1, and eventually 5.0.
- We encountered massive numbers of Hover messages that we never encountered before moving up.  We also were getting a lot of REST failures.
- As a last result we moved back to 5.2.  Seems our take on missing symbols may have been due to poor performance and it was just taking a long time to get things updated.  It seems like when moving up, we have to reload all of the symbols for all of our parts.  
- Hover errors are gone as are the spurious REST errors.
- Another observation although we can't prove it.  The uninstaller for 5.2 seems to have left some 5.2 libs in place.  This is the only explanation for why we started getting Hover messages after moving up to 5.2 and then back to 5.0.

Now the reason why we moved up to 5.2 in the first place.  After updating the Yaml file with our private libs, Hover isn't working.  It is now our understanding that we have to license RDz EE to get this capability.  Simple question.  Why?  RDz EE OOB has more functionality than z Editor.  Yes, VS Code is more widely usable and it is free, but, if you're going to make me pay for functions that are part of RDz EE to get the really useful ones, you've taken away one more reason for not switching from RDz in the first place.

**Comment by phaumer** [comment]
Hello @johntgatesjr 
We added a progress bar now when a lot of macros and include files get loaded as these can be a lot. If the network connection makes it unusable then the resolving of these can be switched off with user settings.

We repacked our commercial product to IBM Developer for z/OS (IDz) Enterprise Edition, which includes both the Eclipse-based and the VS Code-based editors for a while now. Customers can choose which one to use and also switch based on need and capability available. We are gradually trying to unify that collaborative experience, e.g. by adding ZAPP support now also to the Eclipse-based clients.

Z Open Editor is a full editor for COBOL, PL/I, HLASM, REXX, and JCL and the core language editing capabilities are free. They were never free for the Eclipse variant. For the commercial variant of Z Open Editor we are focusing on Enterprise-level capabilities only, that go beyond editing and help teams scale up their development workflows such as running builds and using the build logs for editing, debugging the application, reviewing/sorting/filter resources on z/OS, etc. This also includes the ability to manage macros libraries and pre-scan them for code completion, which we regard as an advanced feature for doing Assembler development needed by teams that develop software on an enterprise level. The core editor for HLASM is free and we hope is being used by students and hobbyist, but the scanning of macros locally and with RSE API remotely is an add on of the enterprise version for professional developers to scale up their development efforts.

**Comment by johntgatesjr** [comment]
Peter, Thanks for the update.  Simple question I need answered for my management that is asking questions.  We switched to VS code from IDzEE primarily for the cost savings.  In our estimation, IDzEE is a much richer experience and we knew we were giving up some things when we moved.  IDzEE is much more than an Eclipse based editor and includes advanced features that  z Editor is not coming close to implementing.  Hover support for included macros is viewed as a critical capability.  Advanced search capability is another.  Based on your response, I think what you are saying is these features and more that add to the experience will be offered as pay features through a IDzEE license.  The simple question is if I have to pay for an IDzEE license to get these features, why not go back to IDzEE to get the complete set of capabilities?  Say what you want about Eclipse, but if the tradeoff is a full feature set, we will likely consider moving back.  We have over a hundred developers using VS Code today for projects deployed with multiple languages across multiple platforms.  I don't classify any of them as "students or hobbyists."  If your message is that VS Code and z Editor when used for z/OS is for students and hobbyists only, I think you have a serious messaging problem.

**Comment by phaumer** [comment]
Our mission was always to provide a modern take on the IDzEE for Eclipse features in VS Code. Although our goal is not to reimplement everything that it provides, but at some point to provide equivalent capabilities within the VS Code design paradigm. I agree that we are not there, yet, but we adding new or improved capabilities for IDzEE on VS Code now almost every month since version 4.0.0 released a year ago. The z/OS resources table, for example, is clearly inspired by the Eclipse Remote System Explorer. Also, some of the Z Open Editor innovations flow back into and improve Eclipse, such as our HLASM language server that is gradually replacing the capabilities in LPEX or our REXX language server. But because there are gaps we are selling both editors in one package so that if there is capability missing, developer can load up the old Eclipse to solve a problem, while they mainly work with VS Code from day to day. You are also getting much more in the EE package in addition to the Z Open Editor Advanced Features discussed above, such as Debug for VS Code, Wazi Deploy using languages that work much better in VS Code, DBB with user build you can run from Z Open Editor. In ADFz you will be even getting the new VS Code extensions for File Manager and Fault Analyzer provided by HCL. You see we are investing in VS Code capabilities, but not all of it is free.

**Comment by phaumer** [comment]
Fixed in v5.3.0. Let us know how it worked for you.

**Comment by johntgatesjr** [comment]
Peter,  Just tried 5.3 out and most of the errors are gone.  We are still seeing this one, however:

[Error - 1:30:07 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at com.ibm.wazi.lsp.hlasm.core.handlers.CompletionHandler.computeCompletionItems(CompletionHandler.java:69)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer.lambda$1(HLASMLanguageServer.java:237)
	... 7 more

TY.

**Comment by sdaimwood** [comment]
Thanks for reporting @johntgatesjr, I've identified the problem as well and will reopen this issue to track when it is fixed. Appreciate your report here.

**Comment by johntgatesjr** [comment]
🙂

**Comment by phaumer** [comment]
Fixed in v5.4.0
