### ISSUE TITLE
[ZCodeScan] The ZAPP zcodescan profile does not support Glob Patterns syntax for the locations property

### ISSUE THREAD

**Issue by DEL-Guillaume** [IBM/zopeneditor-about#576]
## Development environment used

- Z Open Editor version: 6.2.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat OpenShift Dev Spaces
  - [ ] Eclipse Che
- Editor Platform Version: 1.103.2
- Operating System : Windows 11 Entreprise 23H2
- Java Version : 21.0.9
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached : no

## Problem Description

In the configuration of the ZCodeScan profile in the zapp.yaml file, the Locations property is supposed to support Glob Patterns syntax (see https://ibm.github.io/zopeneditor-about/Docs/advanced_zcodescan.html#configuring-zcodescan-rules and https://code.visualstudio.com/docs/editor/glob-patterns).

As a matter of fact, when running a code scan via VSCode, ZCodeScan cannot find the YAML and JAR files of the rules to execute if these files are not specified with their exact names.

### Observed behavior

- #### With glob patterns

The ZCodeScan profile in the zapp.yaml configuration file :
<img width="360" height="333" alt="Image" src="https://github.com/user-attachments/assets/ba9077e7-ae03-44e7-ba55-29666dada061" />

The contents of the zcodescan directory :
<img width="253" height="223" alt="Image" src="https://github.com/user-attachments/assets/cde3d37d-d662-4c19-860a-50b126b08af6" />

The result :
<img width="939" height="41" alt="Image" src="https://github.com/user-attachments/assets/37fd48ea-b2ce-4fe4-878a-1c0ac1b1fd7f" />

- #### With exact files names

The ZCodeScan profile in the zapp.yaml configuration file :
<img width="484" height="329" alt="Image" src="https://github.com/user-attachments/assets/7ecc9953-991c-4781-9b22-d105110e9c02" />

The result :
<img width="1432" height="168" alt="Image" src="https://github.com/user-attachments/assets/fa00444b-a69b-4415-9897-bd6ee5f6f96d" />

### Expected behavior

The execution of a code scan should find the YAML and JAR rules files whose names match the glob pattern criteria.

Thanks

**Comment by jbyibm** [comment]
Hi,
We have an issue that we need to fix.
@phaumer FYI

**Comment by phaumer** [comment]
Oh, I missed this one as it was not listed in the Changelog, but it was fixed in v6.3.0. @DEL-Guillaume could you check if you issue is gone?

**Comment by DEL-Guillaume** [comment]
Hello,

@phaumer I still have the issue.

For exemple, without Glob Patterns it works fine :

<img width="388" height="138" alt="Image" src="https://github.com/user-attachments/assets/a2e07e05-1fb9-4359-8b45-4aec3f39b317" />

<img width="1336" height="44" alt="Image" src="https://github.com/user-attachments/assets/22dff6aa-b9b2-4f14-9e27-6f6d314fb156" />


But with a wildcard like * or **, ZCodeScan doesn't find my yaml file, and applies all defaults rules :

<img width="327" height="137" alt="Image" src="https://github.com/user-attachments/assets/ef8d9a18-2d6c-4e4a-964e-d661b02d362e" />

<img width="1503" height="96" alt="Image" src="https://github.com/user-attachments/assets/753a649a-bee2-40ac-9de2-a42a6e1fc301" />


For your information, my Z Open Editor version is now 6.4.0.

**Comment by jbyibm** [comment]
We will look for this. Can you confirm that you use Windows

**Comment by jbyibm** [comment]
It looks like that when a location starts with a dot, there is an issue.

@DEL-Guillaume  Try something like this:

```
  # ZCodeScan configuration for the SAM workspace
  - name: zcodescan
    type: zcodescan
    settings:
      rules:
        - type: local
          locations:
            - "**/.zcodescan/*-rules.yaml"
      customRuleModels:
        - type: local
          locations:
            - "**/.zcodescan/*-domains.yaml"
```

We will investigate internally.

**Comment by jbyibm** [comment]
@Spratima FYI

**Comment by jbyibm** [comment]
This issue is only on Windows when a location starts with a dot.  It works on Linux.
@Spratima can you try it on macOs.

**Comment by DEL-Guillaume** [comment]
Hello @jbyibm,

> We will look for this. Can you confirm that you use Windows

Yes I confirm that I use Windows.


> It looks like that when a location starts with a dot, there is an issue.
> 
> [@DEL-Guillaume](https://github.com/DEL-Guillaume) Try something like this:
> 
> ```
>   # ZCodeScan configuration for the SAM workspace
>   - name: zcodescan
>     type: zcodescan
>     settings:
>       rules:
>         - type: local
>           locations:
>             - "**/.zcodescan/*-rules.yaml"
>       customRuleModels:
>         - type: local
>           locations:
>             - "**/.zcodescan/*-domains.yaml"
> ```
> 
> We will investigate internally.

I tried this, but it doesn't work neither.

I also tried removing the dot from the directory name and changing the location in the zapp file. but it still doesn't find the rules file.

**Comment by jbyibm** [comment]
It works for me. Is it possible to have your folder tree?

**Comment by DEL-Guillaume** [comment]
> It works for me. Is it possible to have your folder tree?

The path of my workspace :
C:\Dev\Git - XxXxx\Code Review\xxxx9-xxxxxxxx-xxxxxxx-xxxxxxx (projet XXX99 - pour mes tests)

And in my workspace :

<img width="578" height="644" alt="Image" src="https://github.com/user-attachments/assets/15270e49-6d26-4143-8eed-b8deed541bcb" />

**Comment by jbyibm** [comment]
@DEL-Guillaume 

It works for me. I think you know me, so you can email me.

<img width="1441" height="953" alt="Image" src="https://github.com/user-attachments/assets/020518ce-0544-408a-80b8-aa0a0a654fae" />

**Comment by jbyibm** [comment]
Hello @DEL-Guillaume 
Based on your mail, can you confirm that we can close this discussion as it works as expected.
Thanks.

**Comment by DEL-Guillaume** [comment]
Hello @jbyibm,

I confirm that it now works for me.
I needed to entirely reload my workspace, and after that it was OK.

Thanks
